// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dreadds
int dreadds(Rcpp::StringVector config_path_vec, int n_steps, Rcpp::StringVector output_path_vec);
RcppExport SEXP _dreadds_dreadds(SEXP config_path_vecSEXP, SEXP n_stepsSEXP, SEXP output_path_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type config_path_vec(config_path_vecSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< Rcpp::StringVector >::type output_path_vec(output_path_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(dreadds(config_path_vec, n_steps, output_path_vec));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dreadds_dreadds", (DL_FUNC) &_dreadds_dreadds, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_dreadds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
