#!/bin/bash

usage() {
    cat >&2 <<EOF
# Usage: $0 xmin xmax ymin ymax n_cols n_rows nodata_value \\
#        locations_tsv_file values_tsv_file output_dir
#
# Generate rasters of climate variables from point data in text files.
#
# Expects two files as input, both in tab-separated-values format.
# - locations. Must have column headings Lat and Long. Other columns
#   are ignored.
# - values. Corresponding climate values, with one column for each
#   year of interest. Column headings are used to name output
#   directories.
# Both files must have the same number of rows.
#
# The output consists of one raster for each climate value column.
#
# The rasters are generated as 32-bit floating point GeoTIF and put in
# separate directories named with their corresponding column names
# from the values TSV file.
EOF
    exit 1
}

die() {
    echo "$1" >&2
    exit 1
}

[ $# = 10 ] || usage

basedir=$(cd $(dirname "$0")/.. && pwd)

xmin=$1
xmax=$2
ymin=$3
ymax=$4
ncols=$5
nrows=$6
nodata_value=$7
locations_tsv=$8
values_tsv=$9
out=${10} # parent of output dirs.

export PATH="$basedir/bin:$basedir/src:$PATH"

which csv2grid >/dev/null || \
    die "Couldn't find csv2grid. See $basedir/README.md"

wd=$PWD

mkdir -p "$out"
cd "$out" || die "Can't access directory $out"

tmp_dir=$(mktemp -d tsv-rasterize.XXXXXXXXXX)
cleanup() {
    [ -d "$tmp_dir" ] && rm -r "$tmp_dir"
}
trap cleanup EXIT

# create CSV file from TSV locations and corresponding values
(cd "$wd" && \
        cut -f 1-2  "$locations_tsv"  | \
            paste - "$values_tsv"
) | sed -e 's/,/_/g' \
        -e '1s/"//g' \
        -e '1s/[ /]/_/g' \
        -e 's/\t/,/g' \
        -e 's/[[:cntrl:]]//g' \
        > "$tmp_dir/data.csv"

[ -s "$tmp_dir/data.csv" ] || die "Failed to create $tmp_dir/data.csv"

read line1 < "$tmp_dir/data.csv"
[[ "$line1" =~ Long, && "$line1" =~ Lat, ]] || \
    die "Expected column headings Long and Lat on line 1"
columns=${line1//,/ }

# Generate output rasters as GeoTIF
outname=$(basename "${values_tsv%.tsv}").tif

# Create numerically named symlinks in ./steps to make running the model easier
mkdir -p steps

step=0
for col in $columns; do
    [ "$col" = Long -o "$col" = Lat ] && \
        continue
    ((step++))
    mkdir -p "$col" || die "Couldn't create output directory $col in $PWD"
    outfile="$col/$outname"
    [ -s "$outfile" ] && die "$outfile already exists in $PWD"

    [ -e "steps/$step" ] || ln -s  "../$col"  "steps/$step"

    echo -n "$col..." >&2
    csv2grid \
        "$tmp_dir/data.csv" "$col" \
        "$xmin" "$xmax" "$ymin" "$ymax" \
        "$ncols" "$nrows" \
        "$nodata_value" \
         "$col/$outname" || \
        die "csv2grid ... $tmp_dir/data.vrt $col/$outname failed"
done
echo >&2
