# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dreadds <- function(config_path_vec, n_steps, output_path_vec) {
    .Call(`_dreadds_dreadds`, config_path_vec, n_steps, output_path_vec)
}

